apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployd
subjects:
- kind: ServiceAccount
  name: deployd
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
